# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kalat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paikka', models.CharField(max_length=30)),
                ('saaja', models.CharField(max_length=300)),
                ('viehe', models.CharField(max_length=300)),
                ('paino', models.CharField(max_length=10)),
                ('pituus', models.CharField(max_length=10)),
                ('saantipäivä', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
