# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalat', '0002_remove_kalat_saantipäivä'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalat',
            name='kuva',
            field=models.ImageField(default='images/default.png', upload_to='images'),
        ),
    ]
