# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 19:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kalat', '0005_kalat_saantipäivä'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalat',
            name='saantipäivä',
        ),
        migrations.AddField(
            model_name='kalat',
            name='email',
            field=models.EmailField(default='petrus.rimpilainen@luukku.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kalat',
            name='saantipaiva',
            field=models.DateField(default=datetime.datetime(2016, 8, 31, 19, 14, 48, 566360, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
