# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalat', '0006_auto_20160831_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kalat',
            options={'permissions': (('publih', 'Allows publishing of kalats objects'),)},
        ),
    ]
